// <auto-generated />
namespace EShop.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class initialDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initialDB));
        
        string IMigrationMetadata.Id
        {
            get { return "201605230932458_initialDB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
