// <auto-generated />
namespace EShop.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addFK_WH : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addFK_WH));
        
        string IMigrationMetadata.Id
        {
            get { return "201605281519100_addFK_WH"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
